[phases.build]
cmds = ["mvn clean package -DskipTests -DoutputFile=target/mvn-dependency-list.log"]

[phases.start]
cmds = ["java -jar target/mold-lean-management-1.0.0.jar"]

[start]
cmd = "java -jar target/mold-lean-management-1.0.0.jar"
